-- فرحة ريم: مخزن المقالات والفيديوهات التي تتجدد أسبوعياً
create table if not exists public.weekly_content (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('article', 'video')),
  category text not null default 'awareness'
    check (category in ('medical', 'psychological', 'care', 'awareness')),
  title text not null,
  excerpt text,
  image_url text,
  source_name text not null,
  source_url text not null unique,
  published_at timestamptz not null default now(),
  status text not null default 'published'
    check (status in ('draft', 'published', 'archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists weekly_content_kind_published_idx
  on public.weekly_content (kind, published_at desc)
  where status = 'published';

alter table public.weekly_content enable row level security;

drop policy if exists "public reads published weekly content" on public.weekly_content;
create policy "public reads published weekly content"
  on public.weekly_content
  for select
  to anon, authenticated
  using (status = 'published');

-- الكتابة لا تتم من المتصفح؛ وظيفة Netlify تستعمل service role المحفوظ في متغيرات البيئة.
