// ملف بيانات مراكز دعم متلازمة داون بالمغرب
// آخر تحديث: يونيو 2025
// المصادر: Orphanet، Edulink، annuaire-gratuit.ma، مواقع الجمعيات الرسمية

export const CENTERS = [
  {
    id: "amsat-rabat",
    name_ar: "AMSAT — الجمعية المغربية لمساندة ومساعدة الأشخاص ذوي التثلث الصبغي",
    name_fr: "AMSAT — Association Marocaine de Soutien et d'Aide aux personnes Trisomiques",
    city: "الرباط",
    region: "الرباط-سلا-القنيطرة",
    type: "جمعية",
    services: ["تدخل مبكر", "دعم أسري", "تعليم خاص", "مواكبة نفسية", "أنشطة اجتماعية"],
    age_range: "جميع الأعمار",
    address: "مركز صاحب السمو الملكي الأمير مولاي رشيد، 13 شارع صنعاء، الرباط 10000",
    phone: "+212 537 70 69 56",
    whatsapp: "",
    email: "info.amsat@gmail.com",
    website: "www.amsat.ma",
    facebook: "",
    map_link: "https://maps.google.com/?q=13+Rue+Sanaa+Rabat+Maroc",
    verification_status: "مؤكد",
    last_checked: "مارس 2023",
    sources: ["https://www.orpha.net/en/patient-organisations/patient/90494"],
    notes: "مركز تحت إشراف صاحب السمو الملكي الأمير مولاي رشيد. المصدر: Orphanet"
  },
  {
    id: "malaika-rabat",
    name_ar: "مركز ملائكة — الرباط",
    name_fr: "Centre Malaïka Rabat — Trisomie 21",
    city: "الرباط",
    region: "الرباط-سلا-القنيطرة",
    type: "مركز تربوي",
    services: ["تدخل مبكر (6 أشهر - 4 سنوات)", "تعليم خاص", "دعم أسري", "أنشطة رياضية وتربوية"],
    age_range: "من 6 أشهر إلى 18 سنة",
    address: "داخل مدرسة عمومية بحي المحيط، الرباط",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.edulink.ma/association/association-malaika-de-trisomie-rabat-et-sale/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Quartier+Ocean+Rabat",
    verification_status: "جزئياً مؤكد",
    last_checked: "نوفمبر 2021",
    sources: ["https://www.edulink.ma/association/association-malaika-de-trisomie-rabat-et-sale/"],
    notes: "يُدار بتعاون Lions Club Rabat Océan والنادي 11. يستقبل أكثر من 100 طالب. الهاتف يحتاج إلى تأكيد."
  },
  {
    id: "malaika-sale",
    name_ar: "مركز ملائكة — سلا",
    name_fr: "Centre Malaïka Salé — Trisomie 21",
    city: "سلا",
    region: "الرباط-سلا-القنيطرة",
    type: "مركز تربوي",
    services: ["تدخل مبكر", "تعليم خاص", "دعم أسري", "أنشطة رياضية وتربوية"],
    age_range: "من 6 أشهر إلى 18 سنة",
    address: "داخل مدرسة عمومية بحي تابريكت، سلا",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.edulink.ma/association/association-malaika-de-trisomie-rabat-et-sale/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Quartier+Tabriquet+Sale+Maroc",
    verification_status: "جزئياً مؤكد",
    last_checked: "نوفمبر 2021",
    sources: ["https://www.edulink.ma/association/association-malaika-de-trisomie-rabat-et-sale/"],
    notes: "يُدار بتعاون الفصيل 11 للأندية الليون. الهاتف يحتاج إلى تأكيد."
  },
  {
    id: "grand-coeur-sale",
    name_ar: "جمعية القلب الكبير للأطفال ذوي التثلث الصبغي وطيف التوحد — سلا",
    name_fr: "Association Grand Cœur pour enfants trisomiques et spectre autistique",
    city: "سلا",
    region: "الرباط-سلا-القنيطرة",
    type: "مركز شبه طبي وتربوي",
    services: ["تقويم النطق", "علاج نفسي حركي", "كينيزيثيرابي", "دعم نفسي", "تعليم خاص", "وجبات يومية"],
    age_range: "من 4 إلى 16 سنة",
    address: "شارع واد الذهب، فيلا ريدا رقم 37، بتانا — سلا",
    phone: "0661987399",
    whatsapp: "0661987399",
    email: "assograndcoeur09@gmail.com",
    website: "",
    facebook: "",
    map_link: "https://maps.google.com/?q=Rue+Oued+Dahab+Bettana+Sale",
    verification_status: "مؤكد",
    last_checked: "2021",
    sources: ["https://rabatcity.ma/listing/association-grand-coeur-pour-enfants-trisomiques-et-spectre-autistique/"],
    notes: "يستقبل الأطفال من 8:30 إلى 16:00. تقديم وجبات وفطور. برنامج ABA متوفر."
  },
  {
    id: "aamh-casablanca",
    name_ar: "مركز أمل لذوي الإعاقة الذهنية — عين السبع، الدار البيضاء",
    name_fr: "Centre AAMH Ain Sébaâ — Association Amal pour le Handicap Mental",
    city: "الدار البيضاء",
    region: "الدار البيضاء-سطات",
    type: "مركز متخصص",
    services: ["تدخل مبكر", "تعليم خاص", "دعم نفسي", "تقويم النطق", "علاج حركي"],
    age_range: "يحتاج إلى تأكيد",
    address: "طريق الوحدة، الدار البيضاء 20250",
    phone: "+212 522 60 60 04",
    whatsapp: "",
    email: "",
    website: "http://handicapamal.ma/centre-ain-sbaa/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Route+Al+Ouahda+Casablanca+20250",
    verification_status: "مؤكد",
    last_checked: "2024",
    sources: ["http://handicapamal.ma/centre-ain-sbaa/"],
    notes: "مركز متخصص للأطفال ذوي التثلث الصبغي 21 والتوحد."
  },
  {
    id: "anit21-casablanca",
    name_ar: "الجمعية الوطنية لإدماج الأشخاص ذوي التثلث الصبغي 21 (ANIT 21) — الدار البيضاء",
    name_fr: "Association Nationale pour l'Intégration des Trisomiques 21 (ANIT 21)",
    city: "الدار البيضاء",
    region: "الدار البيضاء-سطات",
    type: "جمعية",
    services: ["تعليم خاص", "متابعة طبية", "أنشطة فنية وموسيقية", "دعم نفسي اجتماعي"],
    age_range: "الأطفال ذوو الأسر المعوزة",
    address: "عين الشق، الدار البيضاء — عنوان تقريبي يحتاج إلى تأكيد",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.edulink.ma/association/association-nationale-pour-lintegration-des-trisomiques-21/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Ain+Chock+Casablanca",
    verification_status: "جزئياً مؤكد",
    last_checked: "2019",
    sources: ["https://www.edulink.ma/association/association-nationale-pour-lintegration-des-trisomiques-21/"],
    notes: "لها مراكز في الدار البيضاء، بنغرير، ومراكش. تستهدف الأسر المعوزة. الهاتف يحتاج إلى تأكيد."
  },
  {
    id: "sanad-mohammedia",
    name_ar: "جمعية سَنَد لذوي التثلث الصبغي 21 — المحمدية",
    name_fr: "Association SANAD de la Trisomie 21 — Mohammedia",
    city: "المحمدية",
    region: "الدار البيضاء-سطات",
    type: "جمعية",
    services: ["دعم أسري", "تحسيس وتوعية", "دعم تربوي", "تكوين"],
    age_range: "جميع الأعمار",
    address: "ص.ب 1114 لا كولين، المحمدية",
    phone: "0623659863",
    whatsapp: "0623659863",
    email: "",
    website: "",
    facebook: "https://fb.com/201194907459160",
    map_link: "https://maps.google.com/?q=La+Colline+Mohammedia+Maroc",
    verification_status: "مؤكد",
    last_checked: "2023",
    sources: ["https://www.annuaire-gratuit.ma/associations/association-sante/association-sanad-de-la-trisomie-21-a-mohammedia-s239317.html"],
    notes: "مسؤول الجمعية: البويحياوي إدريسي مسعود."
  },
  {
    id: "malaika-marrakech",
    name_ar: "جمعية ملائكة — مراكش",
    name_fr: "Association Malaïka Marrakech — Trisomie 21",
    city: "مراكش",
    region: "مراكش-آسفي",
    type: "مركز تربوي وشبه طبي",
    services: ["تعليم خاص (3 مستويات)", "تقويم النطق", "علاج نفسي حركي", "كينيزيثيرابي", "دعم نفسي", "فنون تشكيلية", "موسيقى", "تأهيل مهني", "وجبات يومية"],
    age_range: "من 3 إلى 18 سنة",
    address: "مدرسة سيدي بلعباس، الداودية، مراكش",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.association-malaika-marrakech.com",
    facebook: "https://www.facebook.com/malaika.marrakech",
    map_link: "https://maps.google.com/?q=Ecole+Sidi+Belabbas+Daoudiate+Marrakech",
    verification_status: "مؤكد",
    last_checked: "2024",
    sources: [
      "https://www.association-malaika-marrakech.com",
      "https://www.mapnews.ma/fr/actualites/régional/le-centre-malaika-à-marrakech"
    ],
    notes: "تستقبل 110 طفلاً ومراهقاً مجاناً. رئيسة: دريا مزداوي. شريك INDH وأكاديمية التعليم."
  },
  {
    id: "abnaouna-marrakech",
    name_ar: "جمعية أبناؤنا T21 — مراكش",
    name_fr: "Abnaouna T21 — Marrakech",
    city: "مراكش",
    region: "مراكش-آسفي",
    type: "جمعية",
    services: ["دعم أسري", "نقل مدرسي", "إدماج مدرسي", "خدمات تربوية", "تمثيل حقوقي"],
    age_range: "جميع الأعمار",
    address: "مراكش — عنوان تقريبي يحتاج إلى تأكيد",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.nt3awnou.ma/abnaouna-t21-marrakech/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Marrakech+Maroc",
    verification_status: "جزئياً مؤكد",
    last_checked: "2023",
    sources: ["https://www.nt3awnou.ma/abnaouna-t21-marrakech/"],
    notes: "تسعى لبناء مركز اجتماعي خاص. الهاتف والعنوان يحتاجان إلى تأكيد."
  },
  {
    id: "ichraket-qalb-tetouan",
    name_ar: "جمعية إشراقة قلب للأشخاص ذوي التثلث الصبغي وأسرهم — تطوان",
    name_fr: "Association Ichraket Qalb — Trisomie 21 Tétouan",
    city: "تطوان",
    region: "طنجة-تطوان-الحسيمة",
    type: "جمعية",
    services: ["خدمات تربوية", "خدمات شبه طبية", "إدماج في الفضاءات التعليمية", "تكوين وتأهيل", "دعم أسري"],
    age_range: "جميع الأعمار",
    address: "شارع الحسن الثاني، قرب قصر النخيل، عمارة الموساوي، الطابق 3، شقة 12، الشلال — تطوان",
    phone: "",
    whatsapp: "",
    email: "",
    website: "",
    facebook: "https://www.facebook.com/ichrakat.qalb",
    map_link: "https://maps.google.com/?q=Avenue+Hassan+II+Tetouan+Maroc",
    verification_status: "مؤكد",
    last_checked: "2024",
    sources: ["https://www.facebook.com/ichrakat.qalb"],
    notes: "صفحة فيسبوك نشطة. 1698 متابع. الهاتف غير متوفر حالياً."
  },
  {
    id: "anit21-benguerir",
    name_ar: "ANIT 21 — بنغرير",
    name_fr: "ANIT 21 — Centre de Benguerir",
    city: "بنغرير",
    region: "مراكش-آسفي",
    type: "مركز تربوي",
    services: ["تعليم خاص", "متابعة طبية", "أنشطة فنية"],
    age_range: "الأطفال",
    address: "بنغرير — عنوان تقريبي يحتاج إلى تأكيد",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.edulink.ma/association/association-nationale-pour-lintegration-des-trisomiques-21/",
    facebook: "",
    map_link: "https://maps.google.com/?q=Benguerir+Maroc",
    verification_status: "جزئياً مؤكد",
    last_checked: "2019",
    sources: ["https://www.edulink.ma/association/association-nationale-pour-lintegration-des-trisomiques-21/"],
    notes: "فرع من ANIT 21. العنوان والهاتف يحتاجان إلى تأكيد."
  }
];

// مراكز التوجيه العمومية
export const PUBLIC_CENTERS = [
  {
    id: "tanmia-social",
    name_ar: "مراكز التوجيه والمساعدة للأشخاص في وضعية إعاقة — التعاون الوطني",
    name_fr: "Centres d'orientation pour personnes en situation de handicap — Entraide Nationale",
    city: "متعددة المدن",
    region: "وطني",
    type: "مركز توجيه عمومي",
    services: ["توجيه وإرشاد", "دعم اجتماعي", "إحالة لمراكز متخصصة", "مساعدة قانونية"],
    age_range: "جميع الأعمار",
    address: "يتوفر في معظم المدن الكبرى",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.entraide.ma",
    facebook: "",
    map_link: "",
    verification_status: "مؤكد",
    last_checked: "2024",
    sources: ["https://www.entraide.ma"],
    notes: "ليس مخصصاً لمتلازمة داون فقط، لكنه يوجّه الأسر نحو المراكز المتخصصة والخدمات الاجتماعية."
  },
  {
    id: "ministry-solidarity",
    name_ar: "وزارة التضامن والإدماج الاجتماعي والأسرة",
    name_fr: "Ministère de la Solidarité, de l'Insertion sociale et de la Famille",
    city: "الرباط",
    region: "وطني",
    type: "مركز توجيه عمومي",
    services: ["توجيه وطني", "دعم مالي", "تسجيل في الجمعيات المعتمدة"],
    age_range: "جميع الأعمار",
    address: "الرباط",
    phone: "",
    whatsapp: "",
    email: "",
    website: "https://www.social.gov.ma",
    facebook: "",
    map_link: "https://maps.google.com/?q=Ministere+Solidarite+Rabat",
    verification_status: "مؤكد",
    last_checked: "2024",
    sources: ["https://www.social.gov.ma"],
    notes: "للحصول على بطاقة الإعاقة وتسجيل الطفل في المنظومة الاجتماعية الرسمية."
  }
];

// إحصائيات للعرض
export const CENTERS_STATS = {
  total: 11,
  cities: 8,
  verified: 6,
  partial: 5,
  lastUpdate: "يونيو 2025"
};
